import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          "newOrders": "New Orders",
          "productOnRent": "Product on rent",
          "productList": "Product List",
          "cancelledOrders": "Cancelled Orders",
          "transactions": "Transactions",
          "doneButton": "Done",
          "continueButton": "Continue",
          "addProductPlus": "+Add Products",
          "addProductButton": "Add Products",
          "skipAllButton": "Skip All",
          "skip": "Skip",
          "selectCategoriesAppBar": "Select categories",
          "addProductsAppBar": "Add Products",
          "addPicturesAppBar": "Add Pictures",
          "productDetailsAppBar": "Product Detai'ls",
          "orderHistory": "Order History",
          "userProfile": "User Profile",
          "logout": "Logout",
          "businessProfile": "Business Profile",
          "address": "Address",
          "selectServiceArea": "Select Service Area",
          "bankDetails": "Bank Details",
          "individual": "Individual",
          "company": "Company",
          "logo": "logo",
          "ok": "Ok",
          "selectedcategories": "Selected categories",
          "moreCat": "+Add more Categories",
          "cart": "Cart",
          "totalAmt": "Total Amount",
          "dashboard": "Dashboard",
          "myprofile": "My Profile",
          "businessprofile": "Business Profile",
          "settings": "Settings",
          "help": "Help",
          "clearall": "Clear all",
          "all": "All",
          "homeappliance": "Home appliance",
          "computer": "Computer",
          "max": "Max",
          "min": "Mini",
          "selectPrice": "Select Price",
          "categories": "Categories",
          "price": "Price",
          "brand": "Brand",
          "vendors": "Vendors",
          "apply": "Apply",
          "payment": "Payment",
          "call": "Call",
          "cancel": "Cancel",
          "accept": "Accept",
          "userDetails": "User Details",
          "notification": "Notification",
          "totalEarning": "Total Earning",
          "tenantdetails": "Tenant Details",
          "productslist": "Products list",
          "inactive": "Inactive",
          "onRent": "On Rent",
          "userInfo": "User Info",
          "revenue": "Revenue",
          "timeInMin": "Time(in minutes)",
          "completedTime": "Completed Appointments",
          "averageTime": "Average Time",
          "newUser": "New User",
          "repeatUsers": "Repeat users",
          "selectDeliveryAddress": "Select Delivery Address",
          "yourAccoSucessGen": "Your account has been successfully generated",
          "welToRento": "Welcome to Rento",
          "enterMobNo": "Enter your Mobile number",
          "selectCountry": "Select Country",
          "mobNo": "Mobile number",
          "login": "Login",
          "comProf": "Complete your profile",
          "userName": "Username",
          "email": "Email ID",
          "save": "Save",
          "verification": "Verification",
          "enterCode": "Enter Code",
          "changePhoneNumber": "Change Phone Number",
          "verify": "Verify",
          "dontReceiveCode": "Didn't receive the code?",
          "confirmPayment": "Confirm & Payment",
          "savedCards": "Saved Cards",
          "addNewCard": "+Add New Cards",
          "debitCard": "Debit card",
          "wallets": "Wallets",
          "totalPrice": "Total Price",
          "subTotal": "Sub Total",
          "discount": "Discount",
          "deliveryCharges": "Delivery charges",
          "securityCharges": "Security charges",
          "tax": "Tax",
          "payableAmount": "Payable amount",
          "search": "Search",
          "category": "Category",
          "viewAll": "View all",
          "topVendors": "Top Vendors",
          "newListing": "New Listing",
          "book": "Book",
          "termsofUse": "Terms of use",
          "sortBy": "Sort by",
          "filter": "Filter",
          "securityAmt": "Security Amount",
          "addtoCart": "Add to cart",
          "furniture": "Furniture",
          "cars": "Cars",
          "bikes": "Bikes",
          "properties": "Properties",
          "cancellation": "Cancellation / Refunds",
          "startDate": "Start date",
          "endDate": "End date",
          "refunded": "Refunded",
          "orderID": "Order ID",
          "cancelled": "Cancelled",
          "faq": "FAQ",
          "signingupRento": "Signing up Rento",
          "subscription": "Subscription & Orders",
          "delivery": "Delivery & installation",
          "paymentandRefund": "Payment and refund",
          "servicesandMaintenance": "Services and maintenance",
          "changePreferredLanguage": "Change Preferred Language",
          "language_des":
              "Please select other language if you wish to update from English.",
          "recentPayments": "Recent Payments",
          "totalRefund": "Total Refund",
          "totalPaid": "Total paid",
          "overallPayment": "Overall Payment",
          "paymentHistory": "Payment History",
          "myOrders": "My Orders",
          "refundHistory": "Cancelled/Refund History",
          "savedAddress": "Saved Address",
          "paymentMethod": "Payment Method",
          "termsandConditions": "Terms and conditions",
          "edit": "Edit",
          "delete": "Delete",
          "cards": "Cards",
          "introduction": "Introduction",
          "propertyRights": "Intellectual property rights",
          "restrictions": "Restrictions",
          "addCard": "Add New Card",
          "addAddress": "Add New Address",
          "houseNumber": "House number",
          "streetSector": "Street sector",
          "area": "Area",
          "pinCode": "Pincode",
          "mobile": "Mobile",
          "home": "Home",
          "office": "Office",
          "other": "Other",
          "typeOtheroptions": "Type Other options",
          "HOME": "HOME",
          "ORDERS": "ORDERS",
          "WISHLIST": "WISHLIST",
          "PROFILE": "MY PROFILE",
          "orderDet": "Order Details",
          "orderDate": "Order date",
          "active": "Active",
          "confirmed": "Confirmed",
          "proessing": "Processing",
          "completed": "Completed",
          "deliveryAddress": "Delivery Address",
          "priceDetails": "Price Details",
          "paidBy": "Paid by",
          "reasonforcancelorder": "Reason for cancel order",
          "cancelorder": "Cancel order",
          "orderTracking": "Order Tracking",
          "orderStatus": "Order Status",
          "usingonrent": "Using on rent",
          "rentingperiodcompleted": "Renting period completed",
          "renewPlan": "Renew Plan",
          "returntovendor": "Return to vendor",
          "poweredby": "Powered by",
          "userSection": "User Section",
          "serviceProvider": "Service Provider",
          "productCat": "Product categories",
          "done": "Done",
          "english": "English",
          "german": "German",
          "hindi": "Hindi",
          "start": "Let's Start",
          "changLan":
              "You can always change your preferred language in your profile settings.",
          "lan": "Language",
          "selLan": "Select your preferred language",
          "selectStartDate": "Select Start Date",
          "switchTheme": "Switch Theme",
          "day": "day",
          "views": "Views",
          "wishlist": "Wishlist",
          "received": "Received",
          "totalDays": "total Days",
          "selectreason": "Select reason",
          "addNewAdd": "+Add new address",
          "state": "State",
          "city": "City",
          "cardNo": "Card Number",
          "cardname": "Card name",
          "month": "Month",
          "year": "Year",
          "phone": "Phone Number",
          "name": "Name",
          "email1": "Email",
          "phon": "Phone",
          "open": "OPEN",
          "closed": "CLOSED",
          "on": "ON",
          "off": "OFF",
          "recentPay": "Recent Payment",
          "bydc": "By Debit card",
          "totRefund": "Total Refunds",
          "lastUpdate": "Last update : today",
          "totRec": "Total Received",
          "avgtime": "Average time and trend of performance",
          "newuser": "New users and Repeat users",
          "peopleleft": "People left during the queue",
          "renwedDate": "Renewed date",
          "switchtheme": "Switch to White Theme",
          "resend": "Resend code in",
          "sec": "sec",
          "sentSms": "We have sent you an SMS on",
          "sixDig": "with a 6 digit verification code (OTP).",
          "prodDet": "Product Details",
          "prodname": "Product Name",
          "rentalPrice": "Rental Price",
          "desc": "Description",
        },
        "hi_IN": {
          "newOrders": "नए आदेश",
          "productOnRent": "किराए पर उत्पाद",
          "productList": "उत्पादों की सूची",
          "cancelledOrders": "रद्द आदेश",
          "transactions": "लेनदेन",
          "doneButton": "पूर्ण",
          "continueButton": "जारी रखना",
          "addProductPlus": "+उत्पाद जोड़ें",
          "addProductButton": "उत्पाद जोड़ें",
          "skipAllButton": "सभी को छोड़ें",
          "skip": "छोड़ें",
          "selectCategoriesAppBar": "श्रेणियां चुनें",
          "addProductsAppBar": "उत्पाद जोड़ें",
          "addPicturesAppBar": "चित्र जोड़ें",
          "productDetailsAppBar": "उत्पाद विवरण",
          "orderHistory": "आदेश इतिहास",
          "userProfile": "उपयोगकर्ता रूपरेखा",
          "logout": "लॉग आउट",
          "businessProfile": "व्यापार प्रोफ़ाइल",
          "address": "पता",
          "selectServiceArea": "सेवा क्षेत्र का चयन करें",
          "bankDetails": "बैंक विवरण",
          "individual": "व्यक्तिगत",
          "company": "कंपनी",
          "logo": "प्रतीक चिन्ह",
          "ok": "ठीक",
          "selectedcategories": "चयनित श्रेणियां",
          "moreCat": "+और श्रेणियां जोड़ें",
          "cart": "कार्ट",
          "totalAmt": "कुल राशि",
          "dashboard": "डैशबोर्ड",
          "myprofile": "मेरी प्रोफाइल",
          "businessprofile": "व्यापार प्रोफ़ाइल",
          "settings": "समायोजन",
          "help": "मदद करना",
          "clearall": "सभी साफ करें",
          "all": "सभी",
          "homeappliance": "घरेलू उपकरण",
          "computer": "संगणक",
          "max": "मैक्स",
          "min": "छोटा",
          "selectPrice": "कीमत चुनें",
          "categories": "श्रेणियाँ",
          "price": "कीमत",
          "brand": "ब्रैंड",
          "vendors": "विक्रेताओं",
          "apply": "आवेदन करना",
          "payment": "भुगतान",
          "call": "बुलाना",
          "cancel": "रद्द करना",
          "accept": "स्वीकार करना",
          "userDetails": "उपयोगकर्ता की जानकारी",
          "notification": "अधिसूचना",
          "totalEarning": "कुल कमाई",
          "tenantdetails": "किरायेदार विवरण",
          "productslist": "उत्पाद सूची",
          "inactive": "निष्क्रिय",
          "onRent": "किराए पर",
          "userInfo": "उपयोगकर्ता जानकारी",
          "revenue": "आय",
          "timeInMin": "समय (मिनटों में)",
          "completedTime": "पूर्ण नियुक्तियाँ",
          "averageTime": "औसत समय",
          "newUser": "नया उपयोगकर्ता",
          "repeatUsers": "उपयोगकर्ताओं को दोहराएं",
          "selectDeliveryAddress": "वितरण पता चुनें",
          "yourAccoSucessGen": "आपका खाता सफलतापूर्वक जनरेट कर दिया गया है",
          "welToRento": "रेंटो में आपका स्वागत है",
          "enterMobNo": "अपना मोबाइल नंबर दर्ज करें",
          "selectCountry": "देश चुनें",
          "mobNo": "मोबाइल नंबर",
          "login": "लॉग इन करें",
          "comProf": "अपनी प्रोफ़ाइल पूरी करें",
          "userName": "उपयोगकर्ता नाम",
          "email": "ईमेल आईडी",
          "save": "बचाना",
          "verification": "सत्यापन",
          "enterCode": "कोड दर्ज करें",
          "changePhoneNumber": "फ़ोन नंबर बदलें",
          "verify": "सत्यापित करना",
          "dontReceiveCode": "कोड प्राप्त नहीं हुआ?",
          "confirmPayment": "भुगतान की पुष्टि करें",
          "savedCards": "सहेजे गए कार्ड",
          "addNewCard": "+नए कार्ड जोड़ें",
          "debitCard": "डेबिट कार्ड",
          "wallets": "पर्स",
          "totalPrice": "कुल कीमत",
          "subTotal": "उप योग",
          "discount": "छूट",
          "deliveryCharges": "पहुंचाने का शुल्क",
          "securityCharges": "सुरक्षा शुल्क",
          "tax": "कर",
          "payableAmount": "भुगतान योग्य राशि",
          "search": "खोज",
          "category": "श्रेणी",
          "viewAll": "सभी देखें",
          "topVendors": "शीर्ष विक्रेता",
          "newListing": "नया सूचीकरण",
          "book": "किताब",
          "termsofUse": "उपयोग की शर्तें",
          "sortBy": "इसके अनुसार क्रमबद्ध करें",
          "filter": "फ़िल्टर",
          "securityAmt": "सुरक्षा राशि",
          "addtoCart": "कार्ट में जोड़ें",
          "furniture": "फर्नीचर",
          "cars": "कारों",
          "bikes": "बाइक",
          "properties": "गुण",
          "cancellation": "रद्दीकरण / धनवापसी",
          "startDate": "आरंभ करने की तिथि",
          "endDate": "अंतिम तिथि",
          "refunded": "वापसी की गई है",
          "orderID": "आदेश ID",
          "cancelled": "रद्द",
          "faq": "सामान्य प्रश्न",
          "signingupRento": "रेंटो साइन अप करना",
          "subscription": "सदस्यता और आदेश",
          "delivery": "वितरण और स्थापना",
          "paymentandRefund": "भुगतान और धनवापसी",
          "servicesandMaintenance": "सेवाएं और रखरखाव",
          "changePreferredLanguage": "पसंदीदा भाषा बदलें",
          "language_des":
              "यदि आप अंग्रेजी से अपडेट करना चाहते हैं तो कृपया अन्य भाषा चुनें।",
          "recentPayments": "हाल के भुगतान",
          "totalRefund": "कुल धनवापसी",
          "totalPaid": "पूर्ण भुगतान",
          "overallPayment": "कुल भुगतान",
          "paymentHistory": "भुगतान इतिहास",
          "myOrders": "मेरे आदेश",
          "refundHistory": "रद्द/धनवापसी इतिहास",
          "savedAddress": "सहेजा गया पता",
          "paymentMethod": "भुगतान का तरीका",
          "termsandConditions": "नियम और शर्तें",
          "edit": "संपादन करना",
          "delete": "मिटाना",
          "cards": "पत्ते",
          "introduction": "परिचय",
          "propertyRights": "बौद्धिक संपदा अधिकार",
          "restrictions": "प्रतिबंध",
          "addCard": "नया कार्ड जोड़ें",
          "addAddress": "नया पता जोड़ें",
          "houseNumber": "घर का नंबर",
          "streetSector": "स्ट्रीट सेक्टर",
          "area": "क्षेत्र",
          "pinCode": "पिन कोड",
          "mobile": "गतिमान",
          "home": "घर",
          "office": "कार्यालय",
          "other": "अन्य",
          "typeOtheroptions": "अन्य विकल्प टाइप करें",
          "HOME": "घर",
          "ORDERS": "आदेश",
          "WISHLIST": "इच्छा-सूची",
          "PROFILE": "मेरी प्रोफाइल",
          "orderDet": "ऑर्डर का विवरण",
          "orderDate": "आर्डर की तारीख",
          "active": "सक्रिय",
          "confirmed": "की पुष्टि की",
          "proessing": "प्रसंस्करण",
          "completed": "पूरा हुआ",
          "deliveryAddress": "डिलिवरी का पता",
          "priceDetails": "मूल्य विवरण",
          "paidBy": "द्वारा भुगतान",
          "reasonforcancelorder": "आदेश रद्द करने का कारण",
          "cancelorder": "आदेश रद्द",
          "orderTracking": "आदेश ट्रैकिंग",
          "orderStatus": "आदेश की स्थिति",
          "usingonrent": "किराए पर उपयोग करना",
          "rentingperiodcompleted": "किराये की अवधि पूर्ण",
          "renewPlan": "नवीनीकरण योजना",
          "returntovendor": "विक्रेता को वापस करें",
          "poweredby": "द्वारा संचालित",
          "userSection": "उपयोगकर्ता अनुभाग",
          "serviceProvider": "सेवा प्रदाता",
          "productCat": "उत्पाद श्रेणियां",
          "done": "पूर्ण",
          "english": "अंग्रेज़ी",
          "german": "जर्मन",
          "hindi": "हिन्दी",
          "start": "चलो शुरू करते हैं",
          "changLan":
              "आप अपनी प्रोफ़ाइल सेटिंग में कभी भी अपनी पसंदीदा भाषा बदल सकते हैं।",
          "lan": "भाषा",
          "selLan": "अपनी पसंदीदा भाषा चुनें",
          "selectStartDate": "प्रारंभ तिथि चुनें",
          "switchTheme": "थीम स्विच करें",
          "day": "दिन",
          "views": "विचारों",
          "wishlist": "इच्छा-सूची",
          "received": "प्राप्त हुआ",
          "totalDays": "कुल दिन",
          "selectreason": "कारण चुनें",
          "addNewAdd": "+नया पता जोड़ें",
          "state": "राज्य",
          "city": "शहर",
          "cardNo": "कार्ड नंबर",
          "cardname": "कार्ड का नाम",
          "month": "महीना",
          "year": "साल",
          "phone": "फ़ोन नंबर",
          "name": "नाम",
          "email1": "ईमेल",
          "phon": "फ़ोन",
          "open": "खोलना",
          "closed": "बंद किया हुआ",
          "on": "पर",
          "off": "बंद",
          "recentPay": "हाल का भुगतान",
          "bydc": "डेबिट कार्ड द्वारा",
          "totRefund": "कुल धनवापसी",
          "lastUpdate": "अंतिम अपडेट : आज",
          "totRec": "कुल प्राप्त",
          "avgtime": "औसत समय और प्रदर्शन का रुझान",
          "newuser": "नए उपयोगकर्ता और दोहराने वाले उपयोगकर्ता",
          "peopleleft": "कतार में निकले लोग",
          "renwedDate": "नवीनीकृत तिथि",
          "switchtheme": "सफेद थीम पर स्विच करें",
          "resend": "कोड फिर से भेजें",
          "sec": "सेकंड",
          "sentSms": "हमने आपको एक एसएमएस भेजा है",
          "sixDig": "6 अंकों का सत्यापन कोड (ओटीपी) के साथ।",
          "prodDet": "उत्पाद विवरण",
          "prodname": "प्रोडक्ट का नाम",
          "rentalPrice": "किराये की कीमत",
          "desc": "विवरण",
        },
        "de_DE": {
          "newOrders": "Neue Bestellungen",
          "productOnRent": "Produkt auf Miete",
          "productList": "Produktliste",
          "cancelledOrders": "Stornierte Bestellungen",
          "transactions": "Transaktionen",
          "doneButton": "Fertig",
          "continueButton": "Fortsetzen",
          "addProductPlus": "+Produkte hinzufügen",
          "addProductButton": "Produkte hinzufügen",
          "skipAllButton": "Alles überspringen",
          "skip": "Überspringen",
          "selectCategoriesAppBar": "Kategorien auswählen",
          "addProductsAppBar": "Produkte hinzufügen",
          "addPicturesAppBar": "Bilder hinzufügen",
          "productDetailsAppBar": "Produktdetails",
          "orderHistory": "Bestellverlauf",
          "userProfile": "Benutzerprofil",
          "logout": "Ausloggen",
          "businessProfile": "Geschäftsprofil",
          "address": "Adresse",
          "selectServiceArea": "Wählen Sie Servicebereich aus",
          "bankDetails": "Bankdaten",
          "individual": "Individuell",
          "company": "Gesellschaft",
          "logo": "Logo",
          "ok": "OK",
          "selectedcategories": "Ausgewählte Kategorien",
          "moreCat": "+Weitere Kategorien hinzufügen",
          "cart": "Wagen",
          "totalAmt": "Gesamtsumme",
          "dashboard": "Armaturenbrett",
          "myprofile": "Mein Profil",
          "businessprofile": "Geschäftsprofil",
          "settings": "Einstellungen",
          "help": "Hilfe",
          "clearall": "Alles löschen",
          "all": "Alle",
          "homeappliance": "Haushaltsgerät",
          "computer": "Computer",
          "max": "Max",
          "min": "Mini",
          "selectPrice": "Wählen Sie Preis aus",
          "categories": "Kategorien",
          "price": "Preis",
          "brand": "Marke",
          "vendors": "Anbieter",
          "apply": "Sich bewerben",
          "payment": "Zahlung",
          "call": "Anruf",
          "cancel": "Absagen",
          "accept": "Annehmen",
          "userDetails": "Nutzerdetails",
          "notification": "Benachrichtigung",
          "totalEarning": "Gesamtverdienst",
          "tenantdetails": "Mieterdetails",
          "productslist": "Produktliste",
          "inactive": "Inaktiv",
          "onRent": "Auf Miete",
          "userInfo": "Benutzerinformation",
          "revenue": "Einnahmen",
          "timeInMin": "Zeit (in Minuten)",
          "completedTime": "Abgeschlossene Termine",
          "averageTime": "Durchschnittliche Zeit",
          "newUser": "Neuer Benutzer",
          "repeatUsers": "Wiederkehrende Benutzer",
          "selectDeliveryAddress": "Wählen Sie Lieferadresse aus",
          "yourAccoSucessGen": "Ihr Konto wurde erfolgreich erstellt",
          "welToRento": "Willkommen bei Rento",
          "enterMobNo": "Geben sie Ihre Mobilfunknummer ein",
          "selectCountry": "Land auswählen",
          "mobNo": "Handynummer",
          "login": "Anmeldung",
          "comProf": "vervollständige dein Profil",
          "userName": "Nutzername",
          "email": "E-Mail-ID",
          "save": "Speichern",
          "verification": "Überprüfung",
          "enterCode": "Code eingeben",
          "changePhoneNumber": "Telefonnummer ändern",
          "verify": "Verifizieren",
          "dontReceiveCode": "Code nicht erhalten?",
          "confirmPayment": "Bestätige Zahlung",
          "savedCards": "Gespeicherte Karten",
          "addNewCard": "+Neue Karten hinzufügen",
          "debitCard": "Debitkarte",
          "wallets": "Geldbörsen",
          "totalPrice": "Gesamtpreis",
          "subTotal": "Zwischensumme",
          "discount": "Rabatt",
          "deliveryCharges": "Versandkosten",
          "securityCharges": "Sicherheitsgebühren",
          "tax": "Steuer",
          "payableAmount": "Zu zahlender Betrag",
          "search": "Suche",
          "category": "Kategorie",
          "viewAll": "Alle anzeigen",
          "topVendors": "Top-Anbieter",
          "newListing": "Neue Auflistung",
          "book": "Buch",
          "termsofUse": "Nutzungsbedingungen",
          "sortBy": "Sortieren nach",
          "filter": "Filter",
          "securityAmt": "Sicherheitsbetrag",
          "addtoCart": "In den Warenkorb legen",
          "furniture": "Möbel",
          "cars": "Autos",
          "bikes": "Fahrräder",
          "properties": "Eigenschaften",
          "cancellation": "Stornierung / Rückerstattung",
          "startDate": "Anfangsdatum",
          "endDate": "Endtermin",
          "refunded": "Erstattet",
          "orderID": "Auftragsnummer",
          "cancelled": "Abgesagt",
          "faq": "FAQ",
          "signingupRento": "Rento anmelden",
          "subscription": "Abonnement & Bestellungen",
          "delivery": "Lieferung & Montage",
          "paymentandRefund": "Zahlung und Rückerstattung",
          "servicesandMaintenance": "Service und Wartung",
          "changePreferredLanguage": "Bevorzugte Sprache ändern",
          "language_des":
              "Bitte wählen Sie eine andere Sprache, wenn Sie von Englisch aus aktualisieren möchten.",
          "recentPayments": "Letzte Zahlungen",
          "totalRefund": "Gesamtrückerstattung",
          "totalPaid": "Ganz bezahlt",
          "overallPayment": "Gesamtzahlung",
          "paymentHistory": "Zahlungshistorie",
          "myOrders": "Meine Bestellungen",
          "refundHistory": "Storniert/Rückerstattungshistorie",
          "savedAddress": "Gespeicherte Adresse",
          "paymentMethod": "Zahlungsmethode",
          "termsandConditions": "Geschäftsbedingungen",
          "edit": "Bearbeiten",
          "delete": "Löschen",
          "cards": "Karten",
          "introduction": "Einführung",
          "propertyRights": "Rechte an geistigem Eigentum",
          "restrictions": "Beschränkungen",
          "addCard": "Neue Karte hinzufügen",
          "addAddress": "Neue Adresse hinzufügen",
          "houseNumber": "Hausnummer",
          "streetSector": "Straßensektor",
          "area": "Bereich",
          "pinCode": "Geheimzahl",
          "mobile": "Handy, Mobiltelefon",
          "home": "Heim",
          "office": "Büro",
          "other": "Sonstiges",
          "typeOtheroptions": "Geben Sie Andere Optionen ein",
          "HOME": "HEIMAT",
          "ORDERS": "AUFTRÄGE",
          "WISHLIST": "WUNSCHZETTEL",
          "PROFILE": "MEIN PROFIL",
          "orderDet": "Bestelldetails",
          "orderDate": "Bestelldatum",
          "active": "Aktiv",
          "confirmed": "Bestätigt",
          "proessing": "wird bearbeitet",
          "completed": "Abgeschlossen",
          "deliveryAddress": "Lieferadresse",
          "priceDetails": "Preisdetails",
          "paidBy": "Bezahlt von",
          "reasonforcancelorder": "Grund für die Stornierung der Bestellung",
          "cancelorder": "Bestellung stornieren",
          "orderTracking": "Sendungsverfolgung",
          "orderStatus": "Bestellstatus",
          "usingonrent": "Nutzung auf Miete",
          "rentingperiodcompleted": "Mietdauer abgeschlossen",
          "renewPlan": "Plan erneuern",
          "returntovendor": "Rückgabe an den Verkäufer",
          "poweredby": "Unterstützt von",
          "userSection": "Benutzerbereich",
          "serviceProvider": "Dienstleister",
          "productCat": "Produktkategorien",
          "done": "Fertig",
          "english": "Englisch",
          "german": "Deutsch",
          "hindi": "Hindi",
          "start": "Lasst uns beginnen",
          "changLan":
              "Sie können Ihre bevorzugte Sprache jederzeit in Ihren Profileinstellungen ändern.",
          "lan": "Sprache",
          "selLan": "Wählen Sie Ihre bevorzugte Sprache",
          "selectStartDate": "Wählen Sie Startdatum aus",
          "switchTheme": "Thema wechseln",
          "day": "Tag",
          "views": "Ansichten",
          "wishlist": "Wunschzettel",
          "received": "Erhalten",
          "totalDays": "Die Summe an Tagen",
          "selectreason": "Grund auswählen",
          "addNewAdd": "+Neue Adresse hinzufügen",
          "state": "Bundesland",
          "city": "Stadt",
          "cardNo": "Kartennummer",
          "cardname": "Kartenname",
          "month": "Monat",
          "year": "Jahr",
          "phone": "Telefonnummer",
          "name": "Name",
          "email1": "Email",
          "phon": "Telefon",
          "open": "OFFEN",
          "closed": "ABGESCHLOSSEN",
          "on": "AN",
          "off": "AUS",
          "recentPay": "Letzte Zahlung",
          "bydc": "Per Debitkarte",
          "totRefund": "Gesamtrückerstattung",
          "lastUpdate": "Letztes Update: heute",
          "totRec": "Insgesamt erhalten",
          "avgtime": "Durchschnittliche Zeit und Trend der Leistung",
          "newuser": "Neue Benutzer und Wiederholungsbenutzer",
          "peopleleft": "Die Leute gingen während der Warteschlange",
          "renwedDate": "Erneuerter Termin",
          "switchtheme": "Wechseln Sie zum weißen Thema",
          "resend": "Code erneut einsenden",
          "sec": "Sek",
          "sentSms": "Wir haben Ihnen eine SMS an gesendet",
          "sixDig": "mit einem 6-stelligen Verifizierungscode (OTP).",
          "prodDet": "Produktdetails",
          "prodname": "Produktname",
          "rentalPrice": "Mietpreis",
          "desc": "Beschreibung",
        }
      };
}
