name: rento
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  country_code_picker: ^2.0.2
  firebase_auth: ^3.9.0
  firebase_core: ^1.22.0
  flutter:
    sdk: flutter
  flutter_osm_plugin: ^0.40.2
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.1+1
  get: ^4.6.5
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.1.12
  image_picker: ^0.8.5+3
  pinput: ^2.2.11
  shared_preferences: ^2.0.15
  side_navigation: ^1.0.2
  syncfusion_flutter_charts: ^20.2.44
  syncfusion_flutter_datepicker: ^20.2.40
  syncfusion_flutter_sliders: ^20.2.45
  


cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/svgimages/
    - assets/